//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PictureLink { get; set; }
        public int Count { get; set; }
        public string About { get; set; }
        public string ContactUs { get; set; }
        public int ReserveCourierPrice { get; set; }
        public int ReserveTablePrice { get; set; }
    }
}
