//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int FoodId { get; set; }
        public int FoodCount { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Note { get; set; }
        public bool IsPay { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
